### ISSUE TITLE
An error during constructing the pseudo parallel pairs

### ISSUE THREAD

**Issue by FayeXXX** [seq-to-mind/semi-style-transfer#1]
Thank you for your excellent work. 

I'm interested in your code, and when i run find_sentence_Multi_Thread_Yelp.py, in line 94, it seems len(sentence_list_A) != len(sentence_list_B). I follow all your code and data, but don't know why it occurs.

Looking for your reply, and thank you again for your patience.

**Comment by seq-to-mind** [comment]
You can print out the value of len(sentence_list_A) and len(sentence_list_B), and compare the outputs.

**Comment by seq-to-mind** [comment]
You can print out the values of len(sentence_list_A) and len(sentence_list_B), and compare the outputs.

**Comment by FayeXXX** [comment]
Thank you for your quick reply. I try to run directly instead of debugging, and get the appropriate result. I guess that error happens because of the multiprocessing under the debugging mode.

**Comment by FayeXXX** [comment]
Another question,
as mentioned in your paper, you implement both Lexical and Semantic similarity to build  pseudo parallel data. In your code, only lexical similarity is provided, could you please provide me with the semantic similarity.
Your prompt response will be most appreciated. And thank you again for your beautiful code.

**Comment by seq-to-mind** [comment]
See the `find_sentence_Semantic_Match.py` file of semantic matching script.
You may need to debug it, and change the configuration such as model check-points and input data path.

**Comment by FayeXXX** [comment]
Thank you sooo much for sharing your code.
